Repository Project-Lavinia/Lavinia-api, pull requests merged in 2018-07, with the labels that each got.

#1 refactor: remove unused package
  Lavinia-api/Lavinia-api.csproj
Labels: continuous integration

#2 refactor: include data files
  Lavinia-api/Lavinia-api.csproj
Labels: continuous integration

#4 Fixing codacy issues
  Lavinia-api/Controllers/ElectionController.cs
  Lavinia-api/Data/CustomValidation.cs
  Lavinia-api/Data/ElectionInitializer.cs
  Lavinia-api/Program.cs
  Lavinia-api/Startup.cs
  Lavinia-api/Tests/CustomValidationTests.cs
  Lavinia-api/Tests/UtilityTests.cs
  Lavinia-api/Utilities/AlgorithmUtilities.cs
  Lavinia-api/Utilities/CSVUtilities.cs
  Lavinia-api/Utilities/CsvFormats.cs
  Lavinia-api/Utilities/ETNameUtilities.cs
  Lavinia-api/Utilities/FieldParser.cs
  Lavinia-api/Utilities/ModelBuilder.cs
Labels: code style

#3 docs: Add initial readme
  README.md
Labels: documentation

#6 refactor: Make swagger the default route
  Lavinia-api/Startup.cs
Labels: enhancement

#8 chore: Ensure latest language version is used
  Lavinia-api/Lavinia-api.csproj
  Lavinia-api/Properties/launchSettings.json
Labels: enhancement
